# Generated by Django 4.2.7 on 2023-11-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("integrante1", models.CharField(blank=True, max_length=100)),
                ("integrante2", models.CharField(blank=True, max_length=100)),
                ("integrante3", models.CharField(blank=True, max_length=100)),
                ("integrante4", models.CharField(blank=True, max_length=100)),
                ("integrante5", models.CharField(blank=True, max_length=100)),
                ("integrante6", models.CharField(blank=True, max_length=100)),
                ("edicao", models.CharField(default=2023, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notaLayout", models.IntegerField()),
                ("notaFuncionalidade", models.IntegerField()),
                ("notaApresentacao", models.IntegerField()),
                ("comentario", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "equipe",
                    models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to="projeto.equipe"),
                ),
            ],
        ),
    ]
