# Generated by Django 4.2.7 on 2023-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("integrante1", models.CharField(blank=True, max_length=100)),
                ("integrante2", models.CharField(blank=True, max_length=100)),
                ("integrante3", models.CharField(blank=True, max_length=100)),
                ("integrante4", models.CharField(blank=True, max_length=100)),
                ("integrante5", models.CharField(blank=True, max_length=100)),
                ("integrante6", models.CharField(blank=True, max_length=100)),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EquipeAnalise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("integrante1", models.CharField(blank=True, max_length=100)),
                ("integrante2", models.CharField(blank=True, max_length=100)),
                ("integrante3", models.CharField(blank=True, max_length=100)),
                ("integrante4", models.CharField(blank=True, max_length=100)),
                ("integrante5", models.CharField(blank=True, max_length=100)),
                ("integrante6", models.CharField(blank=True, max_length=100)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("aceita", "Aceita"), ("rejeitada", "Recusada")],
                        default="pendente",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
