# Generated by Django 4.2.7 on 2023-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avaliacao",
            old_name="nota",
            new_name="notaApresentacao",
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="notaFuncionalidade",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="notaLayout",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
