# Generated by Django 4.2.7 on 2023-11-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="descricao",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="equipe",
            name="nota",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipeanalise",
            name="descricao",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="equipeanalise",
            name="nota",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
