# Generated by Django 4.2.7 on 2023-11-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projeto", "0002_equipe_descricao_equipe_nota_equipeanalise_descricao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipe",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="equipe",
            name="nota",
        ),
        migrations.RemoveField(
            model_name="equipeanalise",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="equipeanalise",
            name="nota",
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nota", models.IntegerField()),
                ("comentario", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("equipe", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projeto.equipe")),
            ],
        ),
    ]
