# Generated by Django 4.2.7 on 2023-11-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto", "0003_alter_avaliacao_comentario_alter_avaliacao_equipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="comentario",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="notaApresentacao",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="notaFuncionalidade",
            field=models.IntegerField(),
        ),
    ]
