# Generated by Django 4.2.7 on 2023-11-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto", "0003_remove_equipe_descricao_remove_equipe_nota_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="data",
            field=models.DateField(auto_now_add=True),
        ),
    ]
