# Generated by Django 4.2.7 on 2023-11-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto", "0004_alter_avaliacao_comentario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipe",
            name="data",
        ),
        migrations.AddField(
            model_name="equipe",
            name="edicao",
            field=models.CharField(default=2023, max_length=4),
            preserve_default=False,
        ),
    ]
