# Generated by Django 4.2.7 on 2023-11-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto", "0004_alter_equipe_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipeanalise",
            name="data",
            field=models.DateField(auto_now_add=True),
        ),
    ]
